## 00. PyTorch Fundamentals
Resoruce Notebook https://www.learnpytorch.io/00_pytorch_fundamentals/

In [27]:
import torch
# Fundamental Data Science Packages:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.0


If your google instance restarts or you reconfigure your resources, you need to re-run the packages above ^

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using `torch.tensor()` .

`torch.tensor()` is the most common class in PyTorch

https://pytorch.org/docs/stable/tensors.html

In [28]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [29]:
scalar.ndim

0

scalar has no deminsions, its just a single number.
If you want to get the number out of a tensor type:

In [30]:
# Get tensor back as Python Int
scalar.item()

7

In [31]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [32]:
# It has one deminsion
vector.ndim

1

In [33]:
vector.shape

torch.Size([2])

To know how many deminsion it has, count the number of [] pairs

shape by deminsion

2 by 1 elements


In [34]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

All are tensors: Scalar, Vector, Matrix

Anytime you encode data into numbers, it's of a tensor data type

In [35]:
MATRIX.ndim

2

In [36]:
MATRIX[1]

tensor([ 9, 10])

In [37]:
MATRIX.shape

torch.Size([2, 2])

In [38]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [8,2,1]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [8, 2, 1]]])

Most of the time, you won't be writing tensors by hand. Pytorch does that behind the scenes

In [39]:
TENSOR.ndim

3

In [40]:
TENSOR.shape

torch.Size([1, 3, 3])

number of first brackets, number of 2nd brackets, number of elements within the most inner bracket

### Random Tensors

https://pytorch.org/docs/stable/generated/torch.rand.html

Why random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [41]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2384, 0.4142, 0.3980, 0.0276],
        [0.6301, 0.0864, 0.7370, 0.0625],
        [0.5706, 0.1369, 0.8859, 0.5306]])

In [42]:
random_tensor.ndim

2

In [43]:
# Create a random Tensor with Similar Shape to an Image Tensor
random_image_size_tensor = torch.rand(size =(224, 224, 3)) # Height, width, colour Channels (R,G,B) -- there is no order that is needed
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [44]:
torch.rand(size=(3,3))

tensor([[0.0200, 0.7819, 0.5973],
        [0.0494, 0.6019, 0.1126],
        [0.2564, 0.8304, 0.8669]])

### Zeros and Ones

zero: great for masking (hiding) numbers


In [45]:
# Create a Tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
# Create a Tensor of All ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
# Default data type for this numbers is torch.float32
ones.dtype

torch.float32

### Creating a Range of tensors and tensor-like

https://pytorch.org/docs/stable/generated/torch.arange.html

In [49]:
# Use torch.range()
torch.range(0,10)
# Note that this will deprecated soon

/var/folders/99/y6wx3_cs3t7fymkm7ql3pfd00000gn/T/ipykernel_11151/3135236222.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [50]:
# Use torch.arange()
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# Using start, end, step in arange()
torch.arange(start = 0, end = 1000, step = 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [52]:
# Creating tensors-like = creating a an undefined shape of a tensor
# torch.zeros_like()
ten_zeros = one_to_ten = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])