## 00. PyTorch Fundamentals
Resoruce Notebook https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
# Changing from CPU to MPS
# torch.set_default_device(torch.device("mps"))
# Fundamental Data Science Packages:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.0


If your google instance restarts or you reconfigure your resources, you need to re-run the packages above ^

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using `torch.tensor()` .

`torch.tensor()` is the most common class in PyTorch

https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

scalar has no deminsions, its just a single number.
If you want to get the number out of a tensor type:

In [5]:
# Get tensor back as Python Int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# It has one deminsion
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

To know how many deminsion it has, count the number of [] pairs

shape by deminsion

2 by 1 elements


In [9]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

All are tensors: Scalar, Vector, Matrix

Anytime you encode data into numbers, it's of a tensor data type

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [8,2,1]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [8, 2, 1]]])

Most of the time, you won't be writing tensors by hand. Pytorch does that behind the scenes

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

number of first brackets, number of 2nd brackets, number of elements within the most inner bracket

### Random Tensors

https://pytorch.org/docs/stable/generated/torch.rand.html

Why random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5433, 0.6455, 0.7342, 0.6632],
        [0.4972, 0.5229, 0.0299, 0.4685],
        [0.2410, 0.5278, 0.0076, 0.4852]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random Tensor with Similar Shape to an Image Tensor
random_image_size_tensor = torch.rand(size =(224, 224, 3)) # Height, width, colour Channels (R,G,B) -- there is no order that is needed
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
torch.rand(size=(3,3))

tensor([[0.2359, 0.9021, 0.9153],
        [0.1566, 0.4459, 0.8365],
        [0.0886, 0.4960, 0.7181]])

### Zeros and Ones

zero: great for masking (hiding) numbers


In [20]:
# Create a Tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a Tensor of All ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
# Default data type for this numbers is torch.float32
ones.dtype

torch.float32

### Creating a Range of tensors and tensor-like

https://pytorch.org/docs/stable/generated/torch.arange.html

In [24]:
# Use torch.range()
torch.range(0,10)
# Note that this will deprecated soon

/var/folders/99/y6wx3_cs3t7fymkm7ql3pfd00000gn/T/ipykernel_1794/3135236222.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
# Use torch.arange()
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Using start, end, step in arange()
torch.arange(start = 0, end = 1000, step = 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
# Creating tensors-like = creating a an undefined shape of a tensor
# torch.zeros_like()
ten_zeros = one_to_ten = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes
Default tensor DataType is Float32, even when dtype = None

`dtype` = what DataType is the tensor : 
https://pytorch.org/docs/stable/tensors.html - so important that DataType is the first thing that comes up
- ***NOTE:*** Tensor DataTypes is one of the big 3 errors you'll run into with PyTorch & Deep Learning
1. Tensors not right DataType (i.e. computing float16 with float32)
2. Tensors not right shape (i.e. tensor multiplication)
3. Tensors not on right device (i.e. running operations on CPU when written for GPU)

`device` = What device is your tensor on

`requires_grad` = Whether or not to track gradients with this tensors operation


In [28]:
# Float 32 tensor,
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
# NOTE: HOW TO CONVERT A TENSOR TO A DIFFERENT DATA TYPE
# Converting float32 to float16

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
device = float_32_tensor.device
device


device(type='cpu')

In [33]:
test = torch.tensor([1,2,3,4,5,6,7,8,9,10])
test.device

device(type='cpu')

In [34]:
# Sometimes, multipling tensors of different data types actually works
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors (Tensor Attributes)

1. Tensors not right DataType - to get DataType from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from  a tensor, can use `tensor.device`

In [37]:
# Create a Tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9753, 0.6129, 0.1978, 0.4067],
        [0.8726, 0.0645, 0.6875, 0.1620],
        [0.6406, 0.3031, 0.6195, 0.5084]])

In [38]:
# Find out details about some tensor
print(some_tensor)
print("Data Type of some_tensor: ", some_tensor.dtype)
print("Device of some_tensor: ", some_tensor.device)
print("Shape of some_tensor: ", some_tensor.shape)
print("Number of Dimensions of some_tensor: ", some_tensor.ndim)
print("Total Number of Elements in some_tensor: ", some_tensor.numel())
print("Size of some_tensor: ", some_tensor.size()) # This is the same as shape

tensor([[0.9753, 0.6129, 0.1978, 0.4067],
        [0.8726, 0.0645, 0.6875, 0.1620],
        [0.6406, 0.3031, 0.6195, 0.5084]])
Data Type of some_tensor:  torch.float32
Device of some_tensor:  cpu
Shape of some_tensor:  torch.Size([3, 4])
Number of Dimensions of some_tensor:  2
Total Number of Elements in some_tensor:  12
Size of some_tensor:  torch.Size([3, 4])


### Manipuylation of Tensors (Tensor Operations)

Tensor operation include:
* Addition + add something to a tensor
* Subtraction
* Multiplication (Element-wise)
* Division
* Matrix Multiplication

^ A neural network learns from the combination of these functions

There are also built-in tensors from PyTorch however, when you can, use the operators from Python Because they are more understandable

In [39]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
tensor
# Because we didn't reassign the tensor, the original tensor is still the same

tensor([1, 2, 3])

In [42]:
# Now we reassign the tensor the tensor
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [43]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [44]:
# Try out PyTorch's built-in functions
torch.mul(tensor, 10)


tensor([100, 200, 300])

In [45]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix Multiplication 

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplication aka dot product (Common tensor operation inside neural networks )
* More infomation on how to multiply matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html
* Fun animation: http://matrixmultiplication.xyz/


`@` = opertator for matrix multiplication
`matmul()` = multiplying matrices `mm()` is the same
* If PyTorch already as a builtin in function, it is the faster version of that method

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **Outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [46]:
# Element wise multiplication
print(tensor, "* ", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) *  tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [47]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [48]:
# Matrix multiplication by hand
10*10 + 20*20 + 30*30

1400

In [49]:
%%time
tensor @ tensor

CPU times: user 38 µs, sys: 3 µs, total: 41 µs
Wall time: 41 µs


tensor(1400)

In [52]:
%%time # How long does it take to multiply two tensors
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

UsageError: Can't use statement directly after '%%time'!


In [54]:
%%time
torch.matmul(tensor, tensor)
#*Note: It is so much faster to use PyTorch's built-in functions than to write your own functions

CPU times: user 222 µs, sys: 81 µs, total: 303 µs
Wall time: 271 µs


tensor(1400)

### One of the most common errors in Deep Learning is the shape error

In [55]:
torch.matmul(torch.rand(3,4), torch.rand(3,4))
# Because the inner dimensions don't match

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [56]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.8012, 0.9897, 1.0213],
        [0.7905, 0.8929, 0.9065],
        [0.1387, 0.2880, 0.3180]])

In [57]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm() is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [58]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To Fix our tensor shape issues, we can manupliate the shape of one of our tensors using a ***transpose***

A ***Transpose*** switches the axes or dimensions of a given tensor
`<tensor>.T` `.T` stands for transpose

In [59]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [60]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [61]:
# The mm operation works when tensor_B is transposed
print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tesnor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tesnor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Tensor Aggregation: finding the min, max, mean, sum, etc of a tensor

It's called tensor aggregation because you are going from a large to small amount of numbers

In [62]:
# Create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [63]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [64]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [65]:
# Find the mean 
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [66]:
# Now, converting the tensor to float to get mean
torch.mean(x.float()), x.float().mean(), torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
# NOTE torch.mean() function requires a tensor of float32 

(tensor(46.), tensor(46.), tensor(46.), tensor(46.))

In [67]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional minimum and maximum

At what index do we find the min and max

In [68]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [69]:
# At what index does the min value occur.
x.argmin()

tensor(0)

In [70]:
x[0]

tensor(1)

In [71]:
# At what index does the max value occur
x.argmax()

tensor(9)

## Reshaping, stacking, seqeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tesnor of a certain shape but keep the same memory as the original tensor
* Stacking - combining multiple tensors on top of each other ***vstack*** or **hstack** side by side:  https://pytorch.org/docs/stable/generated/torch.stack.html
* Squeeze - removes all `1` dimensions from a tensor: https://pytorch.org/docs/stable/generated/torch.squeeze.html
* Unsqueexe - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

main point of all of these is to manipulate our tensors in some way, to change their shape or change their dimernsion

In [72]:
# Let's create a tensor
a = torch.arange(1.,10.)
a, a.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
# Add an extra Dimension with .reshape()
a_reshaped = x.reshape(1,10)
a_reshaped, a_reshaped.shape
# NOTE: The reshape has to be a multiple of the original shape

(tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]]), torch.Size([1, 10]))

In [74]:
# Change the view
z = a.view(1, 9)
z, a.shape
# View shares the same memory as the original tensor

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([9]))

In [75]:
# NOTE: Changing z will change a (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z, a

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [76]:
# Stack tensors on top of each other
a_stacked = torch.stack([a,a,a,a], dim = 0)
a_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
a_stacked_1 = torch.stack([a,a,a,a], dim = 1)
a_stacked_1

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [78]:
a_stacked_2 = torch.stack([a,a,a,a], dim = 2)
a_stacked_2

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [79]:
# torch.squeeze() = removes all single dimensions from a target tensor
print(f"Previous tensor: {a_reshaped}")
print(f"Previous shape: {a_reshaped.shape}")

# Remove extra dimensions from a_reshaped
a_squeezed = a_reshaped.squeeze()
print(f"\nNew tensor: {a_squeezed}")
print(f"New shape: {a_squeezed.shape}")


Previous tensor: tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
New shape: torch.Size([10])


In [80]:
# torch.unsqueeze() = adds a single dim to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {a_squeezed}")
print(f"Previous shape: {a_squeezed.shape} ")

# Add an extra dimension to a_squeezed
a_unsqueezed = a_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {a_unsqueezed}")
print(f"New shape: {a_unsqueezed.shape}")


Previous tensor: tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
Previous shape: torch.Size([10]) 

New tensor: tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])
New shape: torch.Size([1, 10])


In [81]:
# torch.permute() = rearranges the dimensions of a target tensor in a specified order

In [82]:
a_reshaped.shape

torch.Size([1, 10])

In [83]:
a_reshaped.squeeze()

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [84]:
a_reshaped.squeeze().shape

torch.Size([10])

In [85]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
a_original = torch.rand(size=(224, 224, 3)) # Height, Width, Colour Channels (R,G,B)

# Permute the original tensor to rearrange the axis (or dim) order
a_permuted = a_original.permute(2,0,1) # New order: Colour Channels, Height, Width
# By index
print(f"Previous shape: {a_original.shape}")
print(f"New shape: {a_permuted.shape}") # New shape: (3, 224, 224)

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (Selecting Data From Tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [86]:
#Create a Tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [87]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [89]:
# Let's index on the middle bracket (dim = 1)
x[0][0]
x[0,0] 
# These two are the same

tensor([1, 2, 3])

In [90]:
# Let's index on the most inner bracket (Last dim)
x[0,0,0]

tensor(1)

In [92]:
# You can also use the slicing operator ":" to select "All" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [93]:
# Get all values of 0th and 1st dimensions but but only index 1  of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [94]:
# Get all values of the 0th dimension but only index 1 of the 1st dimension and 2nd dimension
x[:,1,1]

tensor([5])

In [95]:
# Get index 0 of 0th dim and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])