## 00. PyTorch Fundamentals
Resoruce Notebook https://www.learnpytorch.io/00_pytorch_fundamentals/

In [63]:
import torch
# Changing from CPU to MPS
# torch.set_default_device(torch.device("mps"))
# Fundamental Data Science Packages:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.0


If your google instance restarts or you reconfigure your resources, you need to re-run the packages above ^

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using `torch.tensor()` .

`torch.tensor()` is the most common class in PyTorch

https://pytorch.org/docs/stable/tensors.html

In [64]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [65]:
scalar.ndim

0

scalar has no deminsions, its just a single number.
If you want to get the number out of a tensor type:

In [66]:
# Get tensor back as Python Int
scalar.item()

7

In [67]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [68]:
# It has one deminsion
vector.ndim

1

In [69]:
vector.shape

torch.Size([2])

To know how many deminsion it has, count the number of [] pairs

shape by deminsion

2 by 1 elements


In [70]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

All are tensors: Scalar, Vector, Matrix

Anytime you encode data into numbers, it's of a tensor data type

In [71]:
MATRIX.ndim

2

In [72]:
MATRIX[1]

tensor([ 9, 10])

In [73]:
MATRIX.shape

torch.Size([2, 2])

In [74]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [8,2,1]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [8, 2, 1]]])

Most of the time, you won't be writing tensors by hand. Pytorch does that behind the scenes

In [75]:
TENSOR.ndim

3

In [76]:
TENSOR.shape

torch.Size([1, 3, 3])

number of first brackets, number of 2nd brackets, number of elements within the most inner bracket

### Random Tensors

https://pytorch.org/docs/stable/generated/torch.rand.html

Why random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [77]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4116, 0.0207, 0.5931, 0.7194],
        [0.5058, 0.8860, 0.5426, 0.0111],
        [0.9489, 0.7104, 0.0408, 0.8963]])

In [78]:
random_tensor.ndim

2

In [79]:
# Create a random Tensor with Similar Shape to an Image Tensor
random_image_size_tensor = torch.rand(size =(224, 224, 3)) # Height, width, colour Channels (R,G,B) -- there is no order that is needed
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [80]:
torch.rand(size=(3,3))

tensor([[0.3698, 0.8592, 0.0717],
        [0.3592, 0.6758, 0.9113],
        [0.2963, 0.0575, 0.2952]])

### Zeros and Ones

zero: great for masking (hiding) numbers


In [81]:
# Create a Tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [82]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [83]:
# Create a Tensor of All ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [84]:
# Default data type for this numbers is torch.float32
ones.dtype

torch.float32

### Creating a Range of tensors and tensor-like

https://pytorch.org/docs/stable/generated/torch.arange.html

In [85]:
# Use torch.range()
torch.range(0,10)
# Note that this will deprecated soon

/var/folders/99/y6wx3_cs3t7fymkm7ql3pfd00000gn/T/ipykernel_2621/3135236222.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [86]:
# Use torch.arange()
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
# Using start, end, step in arange()
torch.arange(start = 0, end = 1000, step = 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [88]:
# Creating tensors-like = creating a an undefined shape of a tensor
# torch.zeros_like()
ten_zeros = one_to_ten = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes
Default tensor DataType is Float32, even when dtype = None

`dtype` = what DataType is the tensor : 
https://pytorch.org/docs/stable/tensors.html - so important that DataType is the first thing that comes up
- ***NOTE:*** Tensor DataTypes is one of the big 3 errors you'll run into with PyTorch & Deep Learning
1. Tensors not right DataType (i.e. computing float16 with float32)
2. Tensors not right shape (i.e. tensor multiplication)
3. Tensors not on right device (i.e. running operations on CPU when written for GPU)

`device` = What device is your tensor on

`requires_grad` = Whether or not to track gradients with this tensors operation


In [89]:
# Float 32 tensor,
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [90]:
float_32_tensor.dtype

torch.float32

In [91]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [92]:
# NOTE: HOW TO CONVERT A TENSOR TO A DIFFERENT DATA TYPE
# Converting float32 to float16

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [93]:
device = float_32_tensor.device
device


device(type='cpu')

In [94]:
test = torch.tensor([1,2,3,4,5,6,7,8,9,10])
test.device

device(type='cpu')

In [95]:
# Sometimes, multipling tensors of different data types actually works
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [96]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [97]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors (Tensor Attributes)

1. Tensors not right DataType - to get DataType from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from  a tensor, can use `tensor.device`

In [98]:
# Create a Tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2344, 0.9263, 0.2422, 0.9402],
        [0.3107, 0.7233, 0.3119, 0.3886],
        [0.6740, 0.0322, 0.5667, 0.2973]])

In [99]:
# Find out details about some tensor
print(some_tensor)
print("Data Type of some_tensor: ", some_tensor.dtype)
print("Device of some_tensor: ", some_tensor.device)
print("Shape of some_tensor: ", some_tensor.shape)
print("Number of Dimensions of some_tensor: ", some_tensor.ndim)
print("Total Number of Elements in some_tensor: ", some_tensor.numel())
print("Size of some_tensor: ", some_tensor.size()) # This is the same as shape

tensor([[0.2344, 0.9263, 0.2422, 0.9402],
        [0.3107, 0.7233, 0.3119, 0.3886],
        [0.6740, 0.0322, 0.5667, 0.2973]])
Data Type of some_tensor:  torch.float32
Device of some_tensor:  cpu
Shape of some_tensor:  torch.Size([3, 4])
Number of Dimensions of some_tensor:  2
Total Number of Elements in some_tensor:  12
Size of some_tensor:  torch.Size([3, 4])


### Manipuylation of Tensors (Tensor Operations)

Tensor operation include:
* Addition + add something to a tensor
* Subtraction
* Multiplication (Element-wise)
* Division
* Matrix Multiplication

^ A neural network learns from the combination of these functions

There are also built-in tensors from PyTorch however, when you can, use the operators from Python Because they are more understandable

In [100]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [101]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [102]:
tensor
# Because we didn't reassign the tensor, the original tensor is still the same

tensor([1, 2, 3])

In [103]:
# Now we reassign the tensor the tensor
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [104]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [105]:
# Try out PyTorch's built-in functions
torch.mul(tensor, 10)


tensor([100, 200, 300])

In [106]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix Multiplication 

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplication aka dot product (Common tensor operation inside neural networks )
* More infomation on how to multiply matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html
* Fun animation: http://matrixmultiplication.xyz/


`@` = opertator for matrix multiplication
`matmul()` = multiplying matrices `mm()` is the same
* If PyTorch already as a builtin in function, it is the faster version of that method

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **Outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [107]:
# Element wise multiplication
print(tensor, "* ", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) *  tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [108]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [109]:
# Matrix multiplication by hand
10*10 + 20*20 + 30*30

1400

In [110]:
%%time
tensor @ tensor

CPU times: user 91 µs, sys: 117 µs, total: 208 µs
Wall time: 106 µs


tensor(1400)

In [111]:
%%time # How long does it take to multiply two tensors
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

UsageError: Can't use statement directly after '%%time'!


In [ ]:
%%time
torch.matmul(tensor, tensor)
#*Note: It is so much faster to use PyTorch's built-in functions than to write your own functions

CPU times: user 118 µs, sys: 20 µs, total: 138 µs
Wall time: 90.8 µs


tensor(1400)

### One of the most common errors in Deep Learning is the shape error

In [ ]:
torch.matmul(torch.rand(3,4), torch.rand(3,4))
# Because the inner dimensions don't match

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.6154, 0.2427, 0.2208],
        [0.9755, 0.4317, 0.3349],
        [0.7672, 0.0919, 0.3428]])

In [112]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm() is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [113]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To Fix our tensor shape issues, we can manupliate the shape of one of our tensors using a ***transpose***

A ***Transpose*** switches the axes or dimensions of a given tensor
`<tensor>.T` `.T` stands for transpose

In [117]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [116]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [120]:
# The mm operation works when tensor_B is transposed
print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tesnor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tesnor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
