## 00. PyTorch Fundamentals
Resoruce Notebook https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
# Changing from CPU to MPS
# torch.set_default_device(torch.device("mps"))
# Fundamental Data Science Packages:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1


If your google instance restarts or you reconfigure your resources, you need to re-run the packages above ^

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using `torch.tensor()` .

`torch.tensor()` is the most common class in PyTorch

https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

scalar has no deminsions, its just a single number.
If you want to get the number out of a tensor type:

In [4]:
# Get tensor back as Python Int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
# It has one deminsion
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

To know how many deminsion it has, count the number of [] pairs

shape by deminsion

2 by 1 elements


In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

All are tensors: Scalar, Vector, Matrix

Anytime you encode data into numbers, it's of a tensor data type

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [8,2,1]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [8, 2, 1]]])

Most of the time, you won't be writing tensors by hand. Pytorch does that behind the scenes

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

number of first brackets, number of 2nd brackets, number of elements within the most inner bracket

### Random Tensors

https://pytorch.org/docs/stable/generated/torch.rand.html

Why random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [15]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2207, 0.9541, 0.2189, 0.7971],
        [0.9058, 0.1178, 0.3263, 0.3069],
        [0.3431, 0.2859, 0.8202, 0.4323]])

In [16]:
random_tensor.ndim

2

In [17]:
# Create a random Tensor with Similar Shape to an Image Tensor
random_image_size_tensor = torch.rand(size =(224, 224, 3)) # Height, width, colour Channels (R,G,B) -- there is no order that is needed
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
torch.rand(size=(3,3))

tensor([[0.8330, 0.9777, 0.8460],
        [0.5601, 0.7013, 0.2565],
        [0.6213, 0.0689, 0.6978]])

### Zeros and Ones

zero: great for masking (hiding) numbers


In [19]:
# Create a Tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a Tensor of All ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
# Default data type for this numbers is torch.float32
ones.dtype

torch.float32

### Creating a Range of tensors and tensor-like

https://pytorch.org/docs/stable/generated/torch.arange.html

In [23]:
# Use torch.range()
torch.range(0,10)
# Note that this will deprecated soon

/var/folders/vy/qpgsv71x71ndy195yb474r4r0000gn/T/ipykernel_6353/3135236222.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Using start, end, step in arange()
torch.arange(start = 0, end = 1000, step = 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
# Creating tensors-like = creating a an undefined shape of a tensor
# torch.zeros_like()
ten_zeros = one_to_ten = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes
Default tensor DataType is Float32, even when dtype = None

`dtype` = what DataType is the tensor : 
https://pytorch.org/docs/stable/tensors.html - so important that DataType is the first thing that comes up
- ***NOTE:*** Tensor DataTypes is one of the big 3 errors you'll run into with PyTorch & Deep Learning
1. Tensors not right DataType (i.e. computing float16 with float32)
2. Tensors not right shape (i.e. tensor multiplication)
3. Tensors not on right device (i.e. running operations on CPU when written for GPU)

`device` = What device is your tensor on

`requires_grad` = Whether or not to track gradients with this tensors operation


In [27]:
# Float 32 tensor,
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
# NOTE: HOW TO CONVERT A TENSOR TO A DIFFERENT DATA TYPE
# Converting float32 to float16

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
device = float_32_tensor.device
device


device(type='cpu')

In [32]:
test = torch.tensor([1,2,3,4,5,6,7,8,9,10])
test.device

device(type='cpu')

In [33]:
# Sometimes, multipling tensors of different data types actually works
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors (Tensor Attributes)

1. Tensors not right DataType - to get DataType from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from  a tensor, can use `tensor.device`

In [36]:
# Create a Tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8098, 0.0824, 0.0740, 0.5971],
        [0.2100, 0.6878, 0.7609, 0.8886],
        [0.7782, 0.3409, 0.6585, 0.7983]])

In [37]:
# Find out details about some tensor
print(some_tensor)
print("Data Type of some_tensor: ", some_tensor.dtype)
print("Device of some_tensor: ", some_tensor.device)
print("Shape of some_tensor: ", some_tensor.shape)
print("Number of Dimensions of some_tensor: ", some_tensor.ndim)
print("Total Number of Elements in some_tensor: ", some_tensor.numel())
print("Size of some_tensor: ", some_tensor.size()) # This is the same as shape

tensor([[0.8098, 0.0824, 0.0740, 0.5971],
        [0.2100, 0.6878, 0.7609, 0.8886],
        [0.7782, 0.3409, 0.6585, 0.7983]])
Data Type of some_tensor:  torch.float32
Device of some_tensor:  cpu
Shape of some_tensor:  torch.Size([3, 4])
Number of Dimensions of some_tensor:  2
Total Number of Elements in some_tensor:  12
Size of some_tensor:  torch.Size([3, 4])


### Manipuylation of Tensors (Tensor Operations)

Tensor operation include:
* Addition + add something to a tensor
* Subtraction
* Multiplication (Element-wise)
* Division
* Matrix Multiplication

^ A neural network learns from the combination of these functions

There are also built-in tensors from PyTorch however, when you can, use the operators from Python Because they are more understandable

In [38]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [40]:
tensor
# Because we didn't reassign the tensor, the original tensor is still the same

tensor([1, 2, 3])

In [41]:
# Now we reassign the tensor the tensor
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [42]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [43]:
# Try out PyTorch's built-in functions
torch.mul(tensor, 10)


tensor([100, 200, 300])

In [44]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix Multiplication 

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplication aka dot product (Common tensor operation inside neural networks )
* More infomation on how to multiply matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html
* Fun animation: http://matrixmultiplication.xyz/


`@` = opertator for matrix multiplication
`matmul()` = multiplying matrices `mm()` is the same
* If PyTorch already as a builtin in function, it is the faster version of that method

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **Outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [45]:
# Element wise multiplication
print(tensor, "* ", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) *  tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [46]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [47]:
# Matrix multiplication by hand
10*10 + 20*20 + 30*30

1400

In [48]:
%%time
tensor @ tensor

CPU times: user 174 μs, sys: 62 μs, total: 236 μs
Wall time: 229 μs


tensor(1400)

In [49]:
%%time 
# How long does it take to multiply two tensors

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 608 μs, sys: 792 μs, total: 1.4 ms
Wall time: 759 μs


In [50]:
%%time
torch.matmul(tensor, tensor)
#*Note: It is so much faster to use PyTorch's built-in functions than to write your own functions

CPU times: user 163 μs, sys: 51 μs, total: 214 μs
Wall time: 185 μs


tensor(1400)

### One of the most common errors in Deep Learning is the shape error

In [52]:
torch.matmul(torch.rand(3,4), torch.rand(3,4))
# Because the inner dimensions don't match

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [54]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4523, 0.4510, 0.4215],
        [0.7861, 0.8714, 0.8826],
        [0.0393, 0.0404, 0.0386]])

In [55]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm() is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

To Fix our tensor shape issues, we can manupliate the shape of one of our tensors using a ***transpose***

A ***Transpose*** switches the axes or dimensions of a given tensor
`<tensor>.T` `.T` stands for transpose

In [57]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [58]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [59]:
# The mm operation works when tensor_B is transposed
print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tesnor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tesnor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Tensor Aggregation: finding the min, max, mean, sum, etc of a tensor

It's called tensor aggregation because you are going from a large to small amount of numbers

In [60]:
# Create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [61]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [62]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [63]:
# Find the mean 
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [65]:
# Now, converting the tensor to float to get mean
torch.mean(x.float()), x.float().mean(), torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
# NOTE torch.mean() function requires a tensor of float32 

(tensor(46.), tensor(46.), tensor(46.), tensor(46.))

In [66]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional minimum and maximum

At what index do we find the min and max

In [67]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [68]:
# At what index does the min value occur.
x.argmin()

tensor(0)

In [69]:
x[0]

tensor(1)

In [70]:
# At what index does the max value occur
x.argmax()

tensor(9)

## Reshaping, stacking, seqeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tesnor of a certain shape but keep the same memory as the original tensor
* Stacking - combining multiple tensors on top of each other ***vstack*** or **hstack** side by side:  https://pytorch.org/docs/stable/generated/torch.stack.html
* Squeeze - removes all `1` dimensions from a tensor: https://pytorch.org/docs/stable/generated/torch.squeeze.html
* Unsqueexe - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

main point of all of these is to manipulate our tensors in some way, to change their shape or change their dimernsion

In [71]:
# Let's create a tensor
a = torch.arange(1.,10.)
a, a.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [72]:
# Add an extra Dimension with .reshape()
a_reshaped = x.reshape(1,10)
a_reshaped, a_reshaped.shape
# NOTE: The reshape has to be a multiple of the original shape

(tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]]), torch.Size([1, 10]))

In [73]:
# Change the view
z = a.view(1, 9)
z, a.shape
# View shares the same memory as the original tensor

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([9]))

In [74]:
# NOTE: Changing z will change a (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z, a

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [75]:
# Stack tensors on top of each other
a_stacked = torch.stack([a,a,a,a], dim = 0)
a_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
a_stacked_1 = torch.stack([a,a,a,a], dim = 1)
a_stacked_1

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [77]:
a_stacked_2 = torch.stack([a,a,a,a], dim = 2)
a_stacked_2

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [79]:
# torch.squeeze() = removes all single dimensions from a target tensor
print(f"Previous tensor: {a_reshaped}")
print(f"Previous shape: {a_reshaped.shape}")

# Remove extra dimensions from a_reshaped
a_squeezed = a_reshaped.squeeze()
print(f"\nNew tensor: {a_squeezed}")
print(f"New shape: {a_squeezed.shape}")


Previous tensor: tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
New shape: torch.Size([10])


In [80]:
# torch.unsqueeze() = adds a single dim to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {a_squeezed}")
print(f"Previous shape: {a_squeezed.shape} ")

# Add an extra dimension to a_squeezed
a_unsqueezed = a_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {a_unsqueezed}")
print(f"New shape: {a_unsqueezed.shape}")


Previous tensor: tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
Previous shape: torch.Size([10]) 

New tensor: tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])
New shape: torch.Size([1, 10])


In [81]:
# torch.permute() = rearranges the dimensions of a target tensor in a specified order

In [82]:
a_reshaped.shape

torch.Size([1, 10])

In [83]:
a_reshaped.squeeze()

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [84]:
a_reshaped.squeeze().shape

torch.Size([10])

In [85]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
a_original = torch.rand(size=(224, 224, 3)) # Height, Width, Colour Channels (R,G,B)

# Permute the original tensor to rearrange the axis (or dim) order
a_permuted = a_original.permute(2,0,1) # New order: Colour Channels, Height, Width
# By index
print(f"Previous shape: {a_original.shape}")
print(f"New shape: {a_permuted.shape}") # New shape: (3, 224, 224)

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (Selecting Data From Tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [86]:
#Create a Tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [87]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
# Let's index on the middle bracket (dim = 1)
x[0][0]
x[0,0] 
# These two are the same

tensor([1, 2, 3])

In [89]:
# Let's index on the most inner bracket (Last dim)
x[0,0,0]

tensor(1)

In [90]:
# You can also use the slicing operator ":" to select "All" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [91]:
# Get all values of 0th and 1st dimensions but but only index 1  of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [92]:
# Get all values of the 0th dimension but only index 1 of the 1st dimension and 2nd dimension
x[:,1,1]

tensor([5])

In [93]:
# Get index 0 of 0th dim and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [94]:
# Index on x to return 9
print(x[0,2,2])

# Index on x to return 3, 6, 9
print(x[0,:,2])

tensor(9)
tensor([3, 6, 9])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionalioty to interactive with it

* Data in NumPy, want in PyTorch -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.tensor.numpy()`

NumPy's default DataType is float64
PyTorch's default DataType is float32

In [95]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [96]:
array.dtype

dtype('float64')

In [97]:
# PyTorch reflects the data type of the numpy array unless specified otherwise
tensor.dtype

torch.float64

In [98]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [99]:
# change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor
# Tensor remains the same because it is a new value in memory and not a reference to the numpy array

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [100]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [101]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor
# tensor and numpy_tensor don't share the same memory


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility ( Trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a ***random seed***.

Essentially what the random seed does is "Flavour" the randomness

If you are creating random manuel tensors, instiate each time before creating another tensor 

https://pytorch.org/docs/stable/notes/randomness.html

https://en.wikipedia.org/wiki/Random_seed


In [102]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"First random tensor (A):\n{random_tensor_A}")
print(f"\nSecond random tensor (B):\n{random_tensor_B}")
print(f"\nAre they equal? == {random_tensor_A == random_tensor_B}")

First random tensor (A):
tensor([[0.8397, 0.9785, 0.1665, 0.7554],
        [0.7056, 0.7950, 0.8292, 0.1026],
        [0.3783, 0.4847, 0.8205, 0.9297]])

Second random tensor (B):
tensor([[0.0754, 0.3855, 0.0937, 0.4379],
        [0.6380, 0.0964, 0.1096, 0.6023],
        [0.8512, 0.5685, 0.2976, 0.4812]])

Are they equal? == tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [103]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)


print(f"First random tensor (C):\n{random_tensor_C}")
print(f"\nSecond random tensor (D):\n{random_tensor_D}")
print(f"\nAre they equal? == {random_tensor_C == random_tensor_D}")


First random tensor (C):
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Second random tensor (D):
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Are they equal? == tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenees

### 1. Getting a GPU

1. Easiest - Use Google Colab to get a GPU (options to upgrade as well )
2. Use your own GPU - takes a litte bit of setup and requires the investment of purchasing a GPU. there are tons of options. Check out this post for more info or getting started on researching GPU options: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure. These services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documenations 


In [104]:
import torch
torch.cuda.is_available()

False

For PyTorch since it is capable of running compute on the GPU or CPU, it's best practice to:
* Mac: https://pytorch.org/docs/stable/notes/mps.html
* coda: https://pytorch.org/docs/stable/notes/cuda.html#best-practices



In [105]:
# Setup device agnostic code
# for Coda
device = "cuda" if torch.cuda.is_available() else "cpu" # or mps


In [106]:
# NOTE: for mac
device = "mps" if torch.backends.mps.is_available() else "cpu" 

In [107]:
# count number of devices
torch.cuda.device_count()

0

### 3. Putting Tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a CPU results in faster computations.

In [108]:
# Create a tenso (default on the CPU)
tensor = torch.tensor([1,2,3], device = "cpu")
tensor_default = torch.tensor([1,2,3])

print(tensor, tensor.device)
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu
tensor([1, 2, 3]) cpu


In [109]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

0 is the index on the GPU we are using

### 4. Moving tensors to the CPU

BECAUSE NumPy only works on CPU

In [110]:
# If Tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [113]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [114]:
%%time
tensor_on_gpu

CPU times: user 4 μs, sys: 0 ns, total: 4 μs
Wall time: 5.96 μs


tensor([1, 2, 3], device='mps:0')

In [115]:
%%time
tensor_default

CPU times: user 2 μs, sys: 1 μs, total: 3 μs
Wall time: 2.15 μs


tensor([1, 2, 3])